name: Deploy Account Service

on:
  push:
    branches: [develop]
    paths:
      - "apps/services/account-service/**"
      - "back.sh"
      - "platform/docker/demo/Dockerfile.account-service"
      - "platform/docker/demo/docker-compose-demo-app.yml"
      - ".github/workflows/deploy-account-service.yml"
      - ".github/workflows/_deploy-app.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-app.yml
    with:
      app_name: account-service
      deploy_target: backend
      service_name: account-service
    secrets: inherit
