name: Deploy Storage Service

on:
  push:
    branches: [develop]
    paths:
      - "apps/services/storage-service/**"
      - "back.sh"
      - "platform/docker/demo/Dockerfile.storage-service"
      - "platform/docker/demo/docker-compose-demo-app.yml"
      - ".github/workflows/deploy-storage-service.yml"
      - ".github/workflows/_deploy-app.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-app.yml
    with:
      app_name: storage-service
      deploy_target: backend
      service_name: storage-service
    secrets: inherit
