name: Deploy ES Service

on:
  push:
    branches: [develop]
    paths:
      - "apps/services/es-service/**"
      - "back.sh"
      - "platform/docker/demo/Dockerfile.es-service"
      - "platform/docker/demo/docker-compose-demo-app.yml"
      - ".github/workflows/deploy-es-service.yml"
      - ".github/workflows/_deploy-app.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-app.yml
    with:
      app_name: es-service
      deploy_target: backend
      service_name: es-service
    secrets: inherit
